DROP ALL OBJECTS;

CREATE SEQUENCE MEMBER_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE QUESTION_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE UPLOAD_SEQ START WITH 100 INCREMENT BY 1;

CREATE TABLE MEMBER (
    no NUMBER(10) DEFAULT MEMBER_SEQ.NEXTVAL NOT NULL,
    id VARCHAR2(30) NOT NULL,
    password VARCHAR2(100) NOT NULL,
    email VARCHAR2(320) NOT NULL,
    grade NUMBER(2) DEFAULT 1 NOT NULL,
    credential_version NUMBER(10) DEFAULT 0 NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (id),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (email)
);

CREATE TABLE UPLOAD_IMAGE (
    idx NUMBER(10) DEFAULT UPLOAD_SEQ.NEXTVAL NOT NULL,
    id VARCHAR2(30) NOT NULL,
    category NUMBER(2) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name VARCHAR2(255) NOT NULL,
    url VARCHAR2(1024) NOT NULL,
    file_size DOUBLE DEFAULT 0 NOT NULL,
    checked NUMBER(1) DEFAULT 0 NOT NULL,
    u1 NUMBER(1) DEFAULT 0 NOT NULL,
    u2 NUMBER(1) DEFAULT 0 NOT NULL,
    u3 NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_UPLOAD_IMAGE PRIMARY KEY (idx),
    CONSTRAINT UK_UPLOAD_IMAGE_NAME UNIQUE (name),
    CONSTRAINT FK_MEMBER_TO_UPLOAD_IMAGE FOREIGN KEY (id) REFERENCES MEMBER(id)
);

CREATE TABLE QUESTION (
    no NUMBER(10) DEFAULT QUESTION_SEQ.NEXTVAL NOT NULL,
    category NUMBER(2) DEFAULT 30 NOT NULL,
    views NUMBER(5) DEFAULT 0 NOT NULL,
    idx NUMBER(10),
    id VARCHAR2(30) NOT NULL,
    title VARCHAR2(45) NOT NULL,
    content CLOB NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_QUESTION PRIMARY KEY (no),
    CONSTRAINT FK_MEMBER_TO_QUESTION FOREIGN KEY (id) REFERENCES MEMBER(id),
    CONSTRAINT FK_UPLOAD_TO_QUESTION FOREIGN KEY (idx) REFERENCES UPLOAD_IMAGE(idx)
);

CREATE TABLE ANSWER (
    no NUMBER(10) NOT NULL,
    id VARCHAR2(30) NOT NULL,
    content CLOB NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP,
    CONSTRAINT PK_ANSWER PRIMARY KEY (no),
    CONSTRAINT FK_QUESTION_TO_ANSWER FOREIGN KEY (no) REFERENCES QUESTION(no) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_TO_ANSWER FOREIGN KEY (id) REFERENCES MEMBER(id)
);

CREATE TABLE RESULT_IMAGE (
    no NUMBER(10) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    content VARCHAR2(255) NOT NULL,
    url VARCHAR2(1024) NOT NULL,
    CONSTRAINT PK_RESULT_IMAGE PRIMARY KEY (no)
);
