-- Result IDs are explicit application IDs. Model class 0 maps to result 1, etc.
-- Reference artwork is intentionally omitted until a verified, licensed icon set is added.
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (1, 'Speed limit (20 km/h)', '최고속도 20km/h', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (2, 'Speed limit (30 km/h)', '최고속도 30km/h', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (3, 'Speed limit (50 km/h)', '최고속도 50km/h', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (4, 'Speed limit (60 km/h)', '최고속도 60km/h', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (5, 'Speed limit (70 km/h)', '최고속도 70km/h', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (6, 'Speed limit (80 km/h)', '최고속도 80km/h', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (7, 'End of speed limit (80 km/h)', '최고속도 80km/h 제한 해제', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (8, 'Speed limit (100 km/h)', '최고속도 100km/h', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (9, 'Speed limit (120 km/h)', '최고속도 120km/h', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (10, 'No passing', '앞지르기 금지', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (11, 'No passing for vehicles over 3.5 t', '3.5t 초과 차량의 앞지르기 금지', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (12, 'Right-of-way at the next intersection', '다음 교차로 통행 우선', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (13, 'Priority road', '우선도로', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (14, 'Yield', '양보', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (15, 'Stop', '정지 후 양보', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (16, 'No vehicles', '모든 차량 통행 금지', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (17, 'Vehicles over 3.5 t prohibited', '3.5t 초과 자동차 통행 금지', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (18, 'No entry', '진입 금지', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (19, 'General caution', '기타 위험 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (20, 'Dangerous curve to the left', '좌측 위험 커브', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (21, 'Dangerous curve to the right', '우측 위험 커브', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (22, 'Double curve', '연속 커브', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (23, 'Bumpy road', '노면 요철 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (24, 'Slippery road', '미끄러운 도로 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (25, 'Road narrows on the right', '우측 도로 폭 감소', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (26, 'Road work', '도로 공사 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (27, 'Traffic signals', '신호등 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (28, 'Pedestrians', '보행자 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (29, 'Children crossing', '어린이 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (30, 'Bicycles crossing', '자전거 통행 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (31, 'Snow or ice', '눈길 또는 빙판길 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (32, 'Wild animals crossing', '야생동물 출현 주의', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (33, 'End of all speed and passing limits', '모든 구간 제한속도·앞지르기 금지 해제', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (34, 'Turn right ahead', '우회전 지시', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (35, 'Turn left ahead', '좌회전 지시', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (36, 'Ahead only', '직진 지시', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (37, 'Go straight or right', '직진 또는 우회전', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (38, 'Go straight or left', '직진 또는 좌회전', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (39, 'Keep right', '우측 통과 지시', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (40, 'Keep left', '좌측 통과 지시', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (41, 'Roundabout mandatory', '회전교차로 통행', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (42, 'End of no passing', '앞지르기 금지 해제', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (43, 'End of no passing for vehicles over 3.5 t', '3.5t 초과 차량 앞지르기 금지 해제', 'none');
INSERT INTO RESULT_IMAGE (no, name, content, url) VALUES (44, 'Unknown / low-confidence result', '인식 불가 — 표지판을 가깝게 잘라 다시 시도해 주세요', 'none');
